import axios from "axios";
import { CalendarPlus, Check, ChevronDown, MapPin, Users } from "lucide-react";
import { useEffect, useState } from "react";
import { useForm, useWatch } from "react-hook-form";
import { toast } from "sonner";
import { createEvent, getAdminEvents, getColleges, getDepartments } from "../api/admin";
import { Status } from "../components/status";
import type { AdminEvent, RefItem } from "../types/api";

interface FormData {name:string;code:string;description:string;college:string;departments:string[];venueName:string;venueAddress:string;startsAt:string;endsAt:string;registrationOpensAt:string;registrationClosesAt:string;capacity:number;status:"draft"|"published";}
interface ApiErrorBody {error?:{message?:string;details?:Array<{field?:string;message?:string}>}}
const field="focus-ring mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-900 placeholder:text-xs placeholder:text-slate-400 dark:border-white/10 dark:bg-slate-900 dark:text-slate-100 dark:placeholder:text-slate-500 dark:[&>option]:bg-slate-900 dark:[&>option]:text-slate-100";
export const EventsPage=()=>{
  const [events,setEvents]=useState<AdminEvent[]>([]),[colleges,setColleges]=useState<RefItem[]>([]),[departments,setDepartments]=useState<RefItem[]>([]);
  const [departmentsOpen,setDepartmentsOpen]=useState(false);
  const {register,handleSubmit,reset,control,setValue,getValues,formState:{errors,isSubmitting}}=useForm<FormData>({defaultValues:{departments:[],status:"draft"}});
  const college=useWatch({control,name:"college"});
  const selectedDepartments=useWatch({control,name:"departments"})??[];
  register("departments",{validate:value=>value.length>0});
  const load=()=>getAdminEvents().then(setEvents).catch(()=>toast.error("Unable to load events"));
  useEffect(()=>{void load();getColleges().then(setColleges).catch(()=>undefined);},[]);
  useEffect(()=>{setValue("departments",[]);setDepartmentsOpen(false);if(!college){setDepartments([]);return;}getDepartments(college).then(setDepartments).catch(()=>setDepartments([]));},[college,setValue]);
  const submit=async(v:FormData)=>{try{await createEvent({name:v.name,code:v.code.trim().toUpperCase(),description:v.description,college:v.college,departments:v.departments,venue:{name:v.venueName,address:v.venueAddress},startsAt:v.startsAt,endsAt:v.endsAt,registrationOpensAt:v.registrationOpensAt,registrationClosesAt:v.registrationClosesAt,capacity:Number(v.capacity),status:v.status});toast.success("Event created");reset({departments:[],status:"draft"});await load();}catch(error){if(axios.isAxiosError<ApiErrorBody>(error)){const apiError=error.response?.data.error;const detail=apiError?.details?.[0];toast.error(detail?.field?`${detail.field}: ${detail.message??"Invalid value"}`:apiError?.message??"Event could not be created");return;}toast.error("Event could not be created. Please try again.");}};
  return <div><div><p className="text-xs font-extrabold tracking-[.2em] text-lime-700 uppercase dark:text-lime-300">Event setup</p><h1 className="mt-2 font-display text-3xl font-bold tracking-[-.045em]">Events and venues</h1><p className="mt-2 text-sm text-slate-500">Publish a registration window and assign its campus venue.</p></div>
    <div className="mt-7 grid gap-6 xl:grid-cols-[.92fr_1.08fr]"><form onSubmit={e=>void handleSubmit(submit)(e)} className="panel rounded-3xl p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-lime-300 text-ink-950"><CalendarPlus size={19}/></span><h2 className="font-display text-xl font-bold">Create event</h2></div><div className="mt-6 grid gap-4 sm:grid-cols-2">
      <label className="text-sm font-bold">Event name<input placeholder="e.g. Tech Symposium 2026" className={field} {...register("name",{required:true,minLength:3,maxLength:200})}/></label><label className="text-sm font-bold">Event code<input placeholder="e.g. TECH26" className={field} {...register("code",{required:true,pattern:/^[A-Za-z0-9][A-Za-z0-9_-]{2,49}$/})}/></label>
      <label className="text-sm font-bold sm:col-span-2">Description<textarea rows={4} placeholder="Briefly describe the event…" className={`${field} h-auto py-3`} {...register("description",{required:true,minLength:10,maxLength:5000})}/></label>
      <label className="text-sm font-bold">College<select className={field} {...register("college",{required:true})}><option value="">Choose college</option>{colleges.map(c=><option key={c._id} value={c._id}>{c.name}</option>)}</select></label>
      <div className="relative text-sm font-bold">Departments
        <button type="button" disabled={!college} onClick={()=>setDepartmentsOpen(open=>!open)} className={`${field} flex items-center justify-between text-left font-normal disabled:cursor-not-allowed disabled:opacity-50`} aria-haspopup="listbox" aria-expanded={departmentsOpen}>
          <span className={selectedDepartments.length?"truncate text-slate-900 dark:text-slate-100":"text-slate-400 dark:text-slate-500"}>{selectedDepartments.length?`${selectedDepartments.length} department${selectedDepartments.length===1?"":"s"} selected`:college?"Choose departments":"Choose a college first"}</span>
          <ChevronDown size={17} className={`shrink-0 text-slate-400 transition-transform ${departmentsOpen?"rotate-180":""}`}/>
        </button>
        {departmentsOpen&&<div className="absolute z-20 mt-2 max-h-56 w-full overflow-y-auto rounded-xl border border-slate-200 bg-white p-1.5 text-slate-900 shadow-xl shadow-slate-900/10 dark:border-white/10 dark:bg-slate-900 dark:text-slate-100" role="listbox" aria-multiselectable="true">
          {departments.length===0?<p className="px-3 py-2 text-xs font-normal text-slate-500">No departments available</p>:departments.map(department=>{const selected=selectedDepartments.includes(department._id);return <button key={department._id} type="button" role="option" aria-selected={selected} onClick={()=>setValue("departments",selected?selectedDepartments.filter(id=>id!==department._id):[...selectedDepartments,department._id],{shouldValidate:true})} className="flex w-full items-center gap-2.5 rounded-lg px-2.5 py-2 text-left text-sm font-medium hover:bg-lime-50 dark:hover:bg-white/5"><span className={`grid size-5 shrink-0 place-items-center rounded-md border ${selected?"border-lime-500 bg-lime-400 text-ink-950":"border-slate-300 dark:border-slate-600"}`}>{selected&&<Check size={13} strokeWidth={3}/>}</span><span className="truncate">{department.name}</span></button>})}
        </div>}
      </div>
      <label className="text-sm font-bold">Venue name<input placeholder="e.g. Main Auditorium" className={field} {...register("venueName",{required:true,minLength:2,maxLength:200})}/></label><label className="text-sm font-bold">Venue address<input placeholder="e.g. Academic Block, Ground Floor" className={field} {...register("venueAddress",{required:true,minLength:5,maxLength:500})}/></label>
      <label className="text-sm font-bold">Starts at<input type="datetime-local" className={field} {...register("startsAt",{required:true})}/></label><label className="text-sm font-bold">Ends at<input type="datetime-local" className={field} {...register("endsAt",{required:true,validate:value=>new Date(value)>new Date(getValues("startsAt"))})}/></label>
      <label className="text-sm font-bold">Registration opens<input type="datetime-local" className={field} {...register("registrationOpensAt",{required:true})}/></label><label className="text-sm font-bold">Registration closes<input type="datetime-local" className={field} {...register("registrationClosesAt",{required:true,validate:value=>new Date(value)>new Date(getValues("registrationOpensAt"))&&new Date(value)<=new Date(getValues("startsAt"))})}/></label>
      <label className="text-sm font-bold">Capacity<input type="number" min={1} placeholder="e.g. 250" className={field} {...register("capacity",{required:true,valueAsNumber:true})}/></label><label className="text-sm font-bold">Initial status<select className={field} {...register("status")}><option value="draft">Draft</option><option value="published">Published</option></select></label>
    </div>{Object.keys(errors).length>0&&<p className="mt-4 text-xs font-semibold text-rose-500">Complete all required fields with valid values.</p>}<button disabled={isSubmitting} className="mt-6 h-11 w-full rounded-xl bg-ink-950 text-sm font-bold text-white hover:bg-lime-400 hover:text-ink-950 dark:bg-lime-300 dark:text-ink-950">{isSubmitting?"Creating…":"Create event"}</button></form>
    <section><h2 className="font-display text-xl font-bold">Event portfolio</h2><div className="mt-4 grid gap-4">{events.length===0?<div className="panel rounded-2xl p-10 text-center text-sm text-slate-500">No events have been created.</div>:events.map(event=><article key={event._id} className="panel rounded-2xl p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-extrabold tracking-wider text-lime-700 uppercase dark:text-lime-300">{event.code}</p><h3 className="mt-1 font-display text-xl font-bold">{event.name}</h3><p className={`mt-1 text-xs ${event.college?"text-slate-500":"font-semibold text-amber-600 dark:text-amber-300"}`}>{event.college?.name??"College unavailable"}</p></div><Status value={event.status}/></div><div className="mt-5 grid gap-3 text-sm text-slate-600 sm:grid-cols-2 dark:text-slate-300"><p className="flex items-center gap-2"><MapPin size={16}/>{event.venue?.name??"Venue unavailable"}</p><p className="flex items-center gap-2"><Users size={16}/>{event.registrationCount}/{event.capacity} registered</p></div><p className="mt-4 text-xs text-slate-500">{new Date(event.startsAt).toLocaleString("en-IN")} — {new Date(event.endsAt).toLocaleString("en-IN")}</p></article>)}</div></section></div>
  </div>;
};
