import axios from "axios";
import { CalendarPlus, Check, ChevronDown, Edit3, MapPin, Plus, ShieldCheck, Trash2, Users, X } from "lucide-react";
import { useEffect, useState } from "react";
import { useFieldArray, useForm, useWatch } from "react-hook-form";
import { toast } from "sonner";
import { createEvent, deleteEvent, getAdminEvents, getColleges, getDepartments, getEventDeletionRequests, reviewEventDeletion, updateEvent, type EventDeletionRequest } from "../api/admin";
import { useAuth } from "../context/auth";
import { Status } from "../components/status";
import { ImageUpload } from "../components/image-upload";
import type { AdminEvent, MediaAsset, RefItem } from "../types/api";

interface HighlightForm { title: string; description?: string; image?: MediaAsset; teamSize: number; }
interface FormData { name:string; code:string; college:string; departments:string[]; venueName:string; venueAddress:string; startsAt:string; endsAt:string; registrationOpensAt:string; registrationClosesAt:string; capacity:number; status:"draft"|"published"; banner?: MediaAsset; highlights: HighlightForm[]; }
interface ApiErrorBody { error?: { message?:string; details?:Array<{field?:string;message?:string}> } }
const field="focus-ring mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-900 placeholder:text-xs placeholder:text-slate-400 dark:border-white/10 dark:bg-slate-900 dark:text-slate-100 dark:placeholder:text-slate-500 dark:[&>option]:bg-slate-900 dark:[&>option]:text-slate-100";
const emptyHighlight:HighlightForm={title:"",description:"",teamSize:1};
const emptyForm:Partial<FormData>={departments:[],status:"draft",highlights:[emptyHighlight]};

export const EventsPage=()=>{
  const [events,setEvents]=useState<AdminEvent[]>([]),[colleges,setColleges]=useState<RefItem[]>([]),[departments,setDepartments]=useState<RefItem[]>([]),[requests,setRequests]=useState<EventDeletionRequest[]>([]);
  const [departmentsOpen,setDepartmentsOpen]=useState(false),[editing,setEditing]=useState<AdminEvent|null>(null);
  const {user}=useAuth();
  const {register,handleSubmit,reset,control,setValue,getValues,formState:{errors,isSubmitting}}=useForm<FormData>({defaultValues:emptyForm});
  const {fields,append,remove}=useFieldArray({control,name:"highlights"});
  const college=useWatch({control,name:"college"}),selectedDepartments=useWatch({control,name:"departments"})??[];
  const banner=useWatch({control,name:"banner"}),watchedHighlights=useWatch({control,name:"highlights"})??[];
  register("departments",{validate:value=>value.length>0});
  const load=()=>getAdminEvents().then(setEvents).catch(()=>toast.error("Unable to load events"));
  useEffect(()=>{void load();getColleges().then(setColleges).catch(()=>undefined);},[]);
  useEffect(()=>{if(user?.role==="super_admin")getEventDeletionRequests().then(setRequests).catch(()=>undefined);},[user?.role]);
  useEffect(()=>{setDepartmentsOpen(false);if(!college){setDepartments([]);return;}getDepartments(college).then(setDepartments).catch(()=>setDepartments([]));},[college]);
  const payload=(v:FormData)=>{
    const highlights=(v.highlights??[])
      .map(h=>({title:h.title.trim(),...(h.description?.trim()?{description:h.description.trim()}:{}),...(h.image?{image:h.image}:{}),teamSize:Number(h.teamSize)||1}))
      .filter(h=>h.title.length>0);
    return {name:v.name,code:v.code.trim().toUpperCase(),description:highlights[0]?.description??highlights[0]?.title??v.name.trim(),...(v.banner?{banner:v.banner}:{}),highlights,college:v.college,departments:v.departments,venue:{name:v.venueName,address:v.venueAddress},startsAt:v.startsAt,endsAt:v.endsAt,registrationOpensAt:v.registrationOpensAt,registrationClosesAt:v.registrationClosesAt,capacity:Number(v.capacity),status:v.status};
  };
  const submit=async(v:FormData)=>{try{if(editing){await updateEvent(editing._id,payload(v));toast.success("Event updated");}else{await createEvent(payload(v));toast.success("Event created");}setEditing(null);reset(emptyForm);await load();}catch(error){if(axios.isAxiosError<ApiErrorBody>(error)){const detail=error.response?.data.error?.details?.[0],message=error.response?.data.error?.message??"Event could not be saved";toast.error(detail?.field?`${detail.field}: ${detail.message??"Invalid value"}`:message);return;}toast.error("Event could not be saved");}};
  const startEdit=(event:AdminEvent)=>{setEditing(event);reset({name:event.name,code:event.code,college:event.college?._id??"",departments:event.departments?.map(department=>department._id)??[],venueName:event.venue?.name??"",venueAddress:event.venue?.address??"",startsAt:toLocal(event.startsAt),endsAt:toLocal(event.endsAt),registrationOpensAt:toLocal(event.registrationOpensAt),registrationClosesAt:toLocal(event.registrationClosesAt),capacity:event.capacity,status:event.status as "draft"|"published",banner:event.banner,highlights:event.highlights?.length?event.highlights.map(h=>({title:h.title,description:h.description??"",image:h.image,teamSize:h.teamSize??1})):[emptyHighlight]});};
  const remove_=async(event:AdminEvent)=>{if(!window.confirm(`Delete “${event.name}”? This cannot be undone.`))return;try{const password=event.registrationCount>0?window.prompt("This event has registrations. Enter your admin login password to request deletion:"):undefined;if(event.registrationCount>0&&!password)return;await deleteEvent(event._id,password??undefined);toast.success(event.registrationCount>0?"Deletion request sent for super-admin approval":"Event deleted");await load();if(user?.role==="super_admin")setRequests(await getEventDeletionRequests());}catch(error){toast.error(axios.isAxiosError<ApiErrorBody>(error)?error.response?.data.error?.message??"Event could not be deleted":"Event could not be deleted");}};
  const review=async(request:EventDeletionRequest,decision:"approve"|"reject")=>{try{await reviewEventDeletion(request._id,decision);toast.success(decision==="approve"?"Event deleted":"Deletion rejected");setRequests(current=>current.filter(item=>item._id!==request._id));await load();}catch(error){toast.error(axios.isAxiosError<ApiErrorBody>(error)?error.response?.data.error?.message??"Unable to review request":"Unable to review request");}};
  return <div><p className="text-xs font-extrabold tracking-[.2em] text-lime-700 uppercase dark:text-lime-300">Event setup</p><h1 className="mt-2 font-display text-3xl font-bold tracking-[-.045em]">Events and venues</h1><p className="mt-2 text-sm text-slate-500">Publish a registration window and assign its campus venue.</p>
    {user?.role==="super_admin"&&<section className="panel mt-7 rounded-2xl p-5"><div className="flex items-center gap-3"><ShieldCheck size={19} className="text-lime-700 dark:text-lime-300"/><div><h2 className="font-display text-xl font-bold">Deletion approvals</h2><p className="text-xs text-slate-500">Review deletion requests from other admins.</p></div></div>{requests.length===0?<p className="mt-4 text-sm text-slate-500">No pending requests.</p>:<div className="mt-4 grid gap-3">{requests.map(request=><div key={request._id} className="rounded-xl border border-amber-200 bg-amber-50 p-3 dark:border-amber-400/20 dark:bg-amber-400/10"><p className="font-bold">{request.event.name}</p><p className="mt-1 text-xs text-slate-600 dark:text-slate-300">Requested by {request.requestedBy.name} · {request.event.registrationCount} registrations</p><div className="mt-3 flex justify-end gap-2"><button onClick={()=>void review(request,"reject")} className="rounded-lg border border-slate-300 px-3 py-2 text-xs font-bold dark:border-white/10">Reject</button><button onClick={()=>void review(request,"approve")} className="rounded-lg bg-rose-600 px-3 py-2 text-xs font-bold text-white">Approve deletion</button></div></div>)}</div>}</section>}
    <div className="mt-7 grid gap-6 xl:grid-cols-[.92fr_1.08fr]"><form onSubmit={e=>void handleSubmit(submit)(e)} className="panel rounded-3xl p-6"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-lime-300 text-ink-950"><CalendarPlus size={19}/></span><h2 className="font-display text-xl font-bold">{editing?"Edit event":"Create event"}</h2></div>{editing&&<button type="button" onClick={()=>{setEditing(null);reset(emptyForm);}} className="grid size-9 place-items-center rounded-lg text-slate-500 hover:bg-slate-100 dark:hover:bg-white/10"><X size={18}/></button>}</div>
      <div className="mt-6"><ImageUpload label="Event banner image" aspect="banner" value={banner} onChange={value=>setValue("banner",value,{shouldDirty:true})}/></div>
      <div className="mt-6 grid gap-4 sm:grid-cols-2">
      <label className="text-sm font-bold">Event name<input placeholder="e.g. Tech Symposium 2026" className={field} {...register("name",{required:true,minLength:3,maxLength:200})}/></label><label className="text-sm font-bold">Event code<input disabled={Boolean(editing)} placeholder="e.g. TECH26" className={`${field} disabled:opacity-60`} {...register("code",{required:true,pattern:/^[A-Za-z0-9][A-Za-z0-9_-]{2,49}$/})}/></label>
      <label className="text-sm font-bold">College<select className={field} {...register("college",{required:true})}><option value="">Choose college</option>{colleges.map(c=><option key={c._id} value={c._id}>{c.name}</option>)}</select></label><div className="relative text-sm font-bold">Departments<button type="button" disabled={!college} onClick={()=>setDepartmentsOpen(open=>!open)} className={`${field} flex items-center justify-between text-left font-normal disabled:opacity-50`}><span className={selectedDepartments.length?"truncate text-slate-900 dark:text-slate-100":"text-slate-400 dark:text-slate-500"}>{selectedDepartments.length?`${selectedDepartments.length} department${selectedDepartments.length===1?"":"s"} selected`:college?"Choose departments":"Choose a college first"}</span><ChevronDown size={17}/></button>{departmentsOpen&&<div className="absolute z-20 mt-2 max-h-56 w-full overflow-y-auto rounded-xl border border-slate-200 bg-white p-1.5 dark:border-white/10 dark:bg-slate-900">{departments.map(department=>{const selected=selectedDepartments.includes(department._id);return <button key={department._id} type="button" onClick={()=>setValue("departments",selected?selectedDepartments.filter(id=>id!==department._id):[...selectedDepartments,department._id],{shouldValidate:true})} className="flex w-full items-center gap-2 rounded-lg px-2 py-2 text-left text-sm hover:bg-lime-50"><span className={`grid size-5 place-items-center rounded-md border ${selected?"border-lime-500 bg-lime-400":"border-slate-300"}`}>{selected&&<Check size={13}/>}</span>{department.name}</button>})}</div>}</div>
      <label className="text-sm font-bold">Venue name<input className={field} {...register("venueName",{required:true,minLength:2,maxLength:200})}/></label><label className="text-sm font-bold">Venue address<input className={field} {...register("venueAddress",{required:true,minLength:5,maxLength:500})}/></label><label className="text-sm font-bold">Starts at<input type="datetime-local" className={field} {...register("startsAt",{required:true})}/></label><label className="text-sm font-bold">Ends at<input type="datetime-local" className={field} {...register("endsAt",{required:true,validate:value=>new Date(value)>new Date(getValues("startsAt"))})}/></label><label className="text-sm font-bold">Registration opens<input type="datetime-local" className={field} {...register("registrationOpensAt",{required:true})}/></label><label className="text-sm font-bold">Registration closes<input type="datetime-local" className={field} {...register("registrationClosesAt",{required:true})}/></label><label className="text-sm font-bold">Capacity<input type="number" min={1} className={field} {...register("capacity",{required:true,valueAsNumber:true})}/></label><label className="text-sm font-bold">Initial status<select className={field} {...register("status")}><option value="draft">Draft</option><option value="published">Published</option></select></label>
    </div>
      <div className="mt-6 rounded-2xl border border-slate-200 p-4 dark:border-white/10">
        <div className="flex items-center justify-between gap-3"><div><p className="text-sm font-bold">What's happening</p><p className="mt-0.5 text-xs text-slate-500">Add each activity students should know about — its own title, optional description, and banner.</p></div><button type="button" onClick={()=>append({...emptyHighlight})} className="inline-flex shrink-0 items-center gap-1.5 rounded-lg bg-lime-300 px-3 py-2 text-xs font-bold text-ink-950 hover:bg-lime-400"><Plus size={14}/> Add</button></div>
        <div className="mt-4 grid gap-3">{fields.map((item,index)=>
          <div key={item.id} className="rounded-xl border border-slate-200 p-3 dark:border-white/10">
            <div className="flex items-start gap-3">
              <ImageUpload label="Banner (optional)" value={watchedHighlights[index]?.image} onChange={value=>setValue(`highlights.${index}.image`,value,{shouldDirty:true})}/>
              <div className="min-w-0 flex-1 grid gap-2">
                <input placeholder="e.g. Paper Presentation" className={field} {...register(`highlights.${index}.title` as const,{required:true,minLength:2,maxLength:200})}/>
                <textarea rows={2} placeholder="Description (optional)" className={`${field} h-auto py-2`} {...register(`highlights.${index}.description` as const,{maxLength:1000})}/>
                <select className={field} {...register(`highlights.${index}.teamSize` as const,{required:true,valueAsNumber:true})}>{[1,2,3,4,5,6].map(size=><option key={size} value={size}>{size===1?"Team size: 1 person":`Team size: ${size} people`}</option>)}</select>
              </div>
              {fields.length>1&&<button type="button" onClick={()=>remove(index)} className="grid size-8 shrink-0 place-items-center rounded-lg text-rose-500 hover:bg-rose-50 dark:hover:bg-rose-400/10"><Trash2 size={15}/></button>}
            </div>
          </div>
        )}</div>
      </div>
      {Object.keys(errors).length>0&&<p className="mt-4 text-xs font-semibold text-rose-500">Complete all required fields with valid values.</p>}<button disabled={isSubmitting} className="mt-6 h-11 w-full rounded-xl bg-ink-950 text-sm font-bold text-white disabled:opacity-60 dark:bg-lime-300 dark:text-ink-950">{isSubmitting?(editing?"Saving…":"Creating…"):(editing?"Save changes":"Create event")}</button></form>
    <section><h2 className="font-display text-xl font-bold">Event portfolio</h2><div className="mt-4 grid gap-4">{events.length===0?<div className="panel rounded-2xl p-10 text-center text-sm text-slate-500">No events have been created.</div>:events.map(event=><article key={event._id} className="panel overflow-hidden rounded-2xl">{event.banner?.url&&<img src={event.banner.url} alt={event.name} className="h-36 w-full object-cover"/>}<div className="p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-extrabold tracking-wider text-lime-700 uppercase dark:text-lime-300">{event.code}</p><h3 className="mt-1 font-display text-xl font-bold">{event.name}</h3><p className="mt-1 text-xs text-slate-500">{event.college?.name??"College unavailable"}</p></div><Status value={event.status}/></div><div className="mt-5 grid gap-3 text-sm text-slate-600 sm:grid-cols-2 dark:text-slate-300"><p className="flex items-center gap-2"><MapPin size={16}/>{event.venue?.name??"Venue unavailable"}</p><p className="flex items-center gap-2"><Users size={16}/>{event.registrationCount}/{event.capacity} registered</p></div>{event.highlights?.length>0&&<div className="mt-4 grid gap-2 sm:grid-cols-2">{event.highlights.map((highlight,index)=><div key={highlight._id??index} className="flex items-center gap-2 rounded-lg bg-lime-50 p-2 dark:bg-lime-400/10">{highlight.image?.url&&<img src={highlight.image.url} alt={highlight.title} className="size-9 shrink-0 rounded-md object-cover"/>}<div className="min-w-0"><p className="truncate text-xs font-bold text-lime-800 dark:text-lime-300">{highlight.title}</p>{highlight.description&&<p className="truncate text-[11px] text-slate-500 dark:text-slate-400">{highlight.description}</p>}<p className="text-[11px] text-slate-500 dark:text-slate-400">Team size: {highlight.teamSize===1?"1 person":`${highlight.teamSize??1} people`}</p></div></div>)}</div>}<p className="mt-4 text-xs text-slate-500">{new Date(event.startsAt).toLocaleString("en-IN")} — {new Date(event.endsAt).toLocaleString("en-IN")}</p><div className="mt-5 flex justify-end gap-2"><button onClick={()=>startEdit(event)} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold dark:border-white/10"><Edit3 size={14}/> Edit</button><button onClick={()=>void remove_(event)} className="inline-flex items-center gap-2 rounded-lg border border-rose-200 px-3 py-2 text-xs font-bold text-rose-600"><Trash2 size={14}/> Delete</button></div></div></article>)}</div></section></div>
  </div>;
};
const toLocal=(value:string)=>{const date=new Date(value);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);};
